### ISSUE TITLE
KHEOPS_VIEWER_URL vs KHEOPS_UI_VIEWER_URL

### ISSUE THREAD

**Issue by fliem** [OsiriX-Foundation/KheopsOrchestration#2]
The `KHEOPS_VIEWER_URL` in [docker-compose.env](https://github.com/OsiriX-Foundation/KheopsOrchestration/blob/insecure-install/docker/docker-compose.env) does not seem to do anything. Some digging suggests that it should be `KHEOPS_UI_VIEWER_URL`

**Comment by nicolasvandooren** [comment]
You're absolutely right 

And the `KHEOPS_VIEWER_SM_URL` should be `KHEOPS_UI_VIEWER_SM_URL`
